version: 0.2

env:
  parameter-store:
    CODE_ARTIFACT_DOMAIN: /CodeBuild/CodeArtifact/Domain
    CODE_ARTIFACT_DOMAIN_OWNER: /CodeBuild/CodeArtifact/DomainOwner
    CODE_ARTIFACT_REPOSITORY: /CodeBuild/CodeArtifact/Repository

phases:
  install:
    runtime-versions:
      dotnet: latest
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS
      - dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider
      - dotnet codeartifact-creds install

  pre_build:
    commands:
      - dotnet nuget add source -n codeartifact $(aws codeartifact get-repository-endpoint 
        --domain $CODE_ARTIFACT_DOMAIN 
        --domain-owner $CODE_ARTIFACT_DOMAIN_OWNER 
        --repository $CODE_ARTIFACT_REPOSITORY 
        --format nuget 
        --query repositoryEndpoint 
        --output text)"v3/index.json"

  build:
    commands:
      - rm -rf Code/Nuget
      - mkdir Code/Nuget
      - rm -rf Code/Build
      - mkdir Code/Build
      - dotnet publish -o Code/Nuget
      - dotnet build Code/Lambda.csproj -o Build -c Release
      - dotnet pack --no-build --no-restore Code/Lambda.csproj /p:OutputPath=Code/Nuget -o Code/Nuget
      - cd Code/Build
      - zip Lambda.zip *
      - aws s3 cp Lambda.zip s3://imagecolourswap/ImageColourSwapLambda/
      - cd ..
      - dotnet nuget push Nuget/*.nupkg -s codeartifact --skip-duplicate
      
artifacts:
  files:
    - 'Nuget/Lambda.dll'
  name: 'Lambda'